export const timelineData = [
  {
    text: "Project 1",
    className: "ps-sp-top",
    spanText: "01",
    color: "gray",
    duration: "6 Months",
    direction: "top",
    taskbar: [
      { label: "project 1" },
      { subtask: "sub" },
      { label: "project 1" },
      { subtask: "sub" },
      { subtask: "sub" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { subtask: "subtask1" },
      { subtask: "subtask1" },
      { label: "project 1" },
      { label: "project 1" },
    ],
  },
  {
    text: "Project 2",
    className: "ps-sp-bot",
    spanText: "02",
    color: "black",
    duration: "6 Months",
    direction: "bot",
    taskbar: [
      { label: "project 1" },
      { label: "project 1" },
      { subtask: "sub" },
      { subtask: "sub" },
    ],
  },
  {
    text: "Project 3",
    className: "ps-sp-top",
    spanText: "03",
    color: "gray",
    duration: "6 Months",
    direction: "top",
    taskbar: [
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
      { label: "project 1" },
    ],
  },
];

export const dataSetXAxis = [
  "jan",
  "june",
  "jan",
  "june",
  "jan",
  "june",
  "jan",
];
